### ISSUE TITLE
Cityworks 2014 - Base Map - Choices Do Not Work

### ISSUE THREAD

**Issue by dmcspaden** [JMurk/Cityworks2014_Testing#1]
The default map works.  Selecting other base maps does nothing.

![selectbasemap](https://cloud.githubusercontent.com/assets/9657650/4978439/a8967396-68ef-11e4-81e9-c95a2f6a393a.png)

**Comment by JMurk** [comment]
Found to be a bug on Azteca's side.  Please try now.

*Note that you must turn of the "ESRI Base Map" in the legend in order to see the other base maps.
