### ISSUE TITLE
Interface - SR Comments Updates

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks2014_Testing#12]
Please add functionality to send an activity (code = CWSRCOMM) whenever a comment is INSERTED for a request.  The outcome code should always be UPDATED.

**Comment by BC89** [comment]
done

**Comment by JMurk** [comment]
Each activity sent for SR comment update has the same details, which is the first comment.

![image](https://cloud.githubusercontent.com/assets/5805454/10194720/482f1cde-6758-11e5-8308-f114a22089c3.png)

**Comment by JMurk** [comment]
Confirmed complete.
