### ISSUE TITLE
Interface - Activities - Due Date

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks2014_Testing#15]
Please populate Due Date with PROJFINISHDATE from the Work Order.  This can be on every WO type activity.
![image](https://cloud.githubusercontent.com/assets/5805454/10165702/96837ca6-668e-11e5-9ea7-e5c510166fc4.png)

**Comment by BC89** [comment]
please indicate in the xml message where this should go. i don't see it.

**Comment by JMurk** [comment]
Not available in XML.  Closing
