### ISSUE TITLE
Interface - Activity Details - Add WO ID

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks2014_Testing#17]
If possible, please add the Work Order ID, prefaced by "WO ID:" to the beginning of each activity detail.  This is how the current interface is configured.

It should be something like:

WO: 207654 BY MURK, JOE New CDR

**Comment by JMurk** [comment]
This one is in the text twice?  Also, there is a comma at the front:

Details:  , WO ID: 208546 
From Request 142734:
Code: STORMINL
Description: WW Storm Inlet Choke
Details: 
Comments: By MURK, JOE: 9/30/2015 9:07:46 AM
STANDARD

By MURK, JOE: 9/30/2015 9:21:46 AM
Test, Dispatched to Scout

By MURK, JOE: 9/30/2015 9:23:36 A, WO ID: 208546 M
Test, Dispatched to Scout

By MURK, JOE: 9/30/2015 9:24:09 AM
Test, in Progress
, WO ID: 208546 
By MURK, JOE: 9/30/2015 9:25:18 AM
test actual finish date

**Comment by BC89** [comment]
try now. not sure it's fixed but give it a go.

**Comment by JMurk** [comment]
Looks like that solved it - Confirmed complete.
