### ISSUE TITLE
Interface - Activity Updates

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks2014_Testing#18]
We need to update our procedures so that existing activities are updated after they are created.  Updated should occur when a corresponding Work Order's status is updated to:

-CLOSED
-COMPLETE
-O-OPEN
-O-NEW

and also when new comments are added.  Those comments should be appended to the existing activity details.

Per Doug Walkinshaw:
"You would get the ID values back in the XAPPSR_C event (that shows the post-append state of the full service request including activity ID values).  Then, you would send us XUPDSR events to update those activities."

**Comment by jsomerville** [comment]
This is a pretty big enhancement as it requires configuring and listening to another event from the App Hub to get the Motorola work order id, storing it somewhere on the City side, and altering the Activities XML payloads to detect if a new Activity or an update.

**Comment by JMurk** [comment]
Please prioritize this enhancement.

**Comment by JMurk** [comment]
Tabling this for now.  I think users are happy with the current interface.
