### ISSUE TITLE
Interface - Map Priority

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks2014_Testing#19]
We need to translate the priority values between CSR and Cityworks so that the information can be transferred between the two systems.  Here is the mapping, per Motorola spreadsheet:

![image](https://cloud.githubusercontent.com/assets/5805454/10195138/2b771806-675a-11e5-85b8-282fbf2586d4.png)

Also, please remove the priority text from the comments field.

**Comment by jsomerville** [comment]
Fixed and deployed to City.

**Comment by JMurk** [comment]
Please make the following changes:

   , "MAYOR":"8"
   , "POLICE":"3"
   , "SAFEZONE":"3"
   , "SCHOOL":"3"
   , "COUNCIL":"6"
   , "PRIORITY":"6"
   ,"DIRECTOR":"7"
   ,"GATEWAY":"3"

**Comment by JMurk** [comment]
Complete
