### ISSUE TITLE
Cityworks 2014 - Work Order - Cannot attach or retrieve photos

### ISSUE THREAD

**Issue by dmcspaden** [JMurk/Cityworks2014_Testing#2]
On drag and drop of a photo, an entry for the photo appears but there is no thumbnail and you cannot open it.
On +Add attachments... an entry for the photo appears but there is no thumbnail and you cannot open it.
If you try to open the attachment you get a 403 Forbidden

**Comment by JMurk** [comment]
Fixed, please test and confirm.  Close once confirmed.

**Comment by dmcspaden** [comment]
Tested and found good.
