### ISSUE TITLE
Cityworks Activity Browser - Configure Test Site

### ISSUE THREAD

**Issue by JMurk** [JMurk/Cityworks2014_Testing#23]
Please configure the Cityworks Activity browser on the test site.  This should write to/leverage the Cityworks test database.

The new dev server is dpw-cw2014-dev

**Comment by jday3** [comment]
Is there a dns entry for the new server or are we just going to be accessing it internally on the city network?

**Comment by JMurk** [comment]
Please:
-Update per Ian's email.
-Remap to the DPW_Cityworks database on the BALT-SQL-DEV
-Update the link in the dev portal

**Comment by JMurk** [comment]
Confirmed complete
