### ISSUE TITLE
Cityworks 2014 - Service Request -  Geocode 200 N Holliday St does nothing.

### ISSUE THREAD

**Issue by dmcspaden** [JMurk/Cityworks2014_Testing#4]
I tried to geocode a service request for my office.  When I click on the geocode button it greys out for a while and that is it.  I tried all caps and entering the street name exactly as it appears in the base map with and with out the N for north.
200 Holliday St
200 N HOLLIDAY ST
200 HOLLIDAY ST

![200nholliday](https://cloud.githubusercontent.com/assets/9657650/4978911/52990216-68f3-11e4-873f-18440b7ffa7b.png)

**Comment by JMurk** [comment]
Works fine for me.  Please try again. 
![image](https://cloud.githubusercontent.com/assets/5805454/4982501/284441b8-6913-11e4-9922-eb18873988b5.png)

**Comment by dmcspaden** [comment]
It works in Chrome this afternoon.  It did not work in IE this morning.
