### ISSUE TITLE
CityWorks 2014 - Service Request - Useless street names pop up when entering an address

### ISSUE THREAD

**Issue by dmcspaden** [JMurk/Cityworks2014_Testing#5]
When typing in an address useless street names try to auto populate.  It is the same ones every time.

![uselessaddresspopup](https://cloud.githubusercontent.com/assets/9657650/4979036/27819d8a-68f4-11e4-96d4-994c6e1bc4b1.png)

**Comment by JMurk** [comment]
Non-issue.

**Comment by dmcspaden** [comment]
It not an issue, certainly an annoyance.  A lot of street names end with the ST suffix and Cityworks unhelpfully tries to put in ST CLOUD every single time.
