### ISSUE TITLE
Cirtyworks 2014 - Work Order - Map no longer scrolls to or shows work order locations

### ISSUE THREAD

**Issue by dmcspaden** [JMurk/Cityworks2014_Testing#6]
In the old version the map jumps to the location of my work order.  That doesn't happen now.  The dot isn't on the map either.  For example, work order 166906 has attached assets and an X,Y location but don't see the dot on the map.  The geocode button does nothing.

**Comment by JMurk** [comment]
Works fine for me.  Note that the pin is grey and very difficult to see at times.

![image](https://cloud.githubusercontent.com/assets/5805454/4982376/4be6f846-6912-11e4-9f47-0175d093791c.png)

**Comment by dmcspaden** [comment]
Works now, but now I'm using Chrome. This morning I was using IE.
