### ISSUE TITLE
Cityworks 2014 - Geocode Does Nothing

### ISSUE THREAD

**Issue by dmcspaden** [JMurk/Cityworks2014_Testing#7]
Cityworks 2014 used to return multiple points for a geocode.  Now it doesn't do anything.  I've tried it from Service Requests and Work Orders.

**Comment by JMurk** [comment]
Seems to work fine for me.  Do you have a specific example?

**Comment by dmcspaden** [comment]
Works now in Chrome.  Did not work in IE this morning.
