### ISSUE TITLE
CityWorks 2014 Service Request Geocode returns too many points.

### ISSUE THREAD

**Issue by dmcspaden** [JMurk/Cityworks2014_Testing#8]
When creating an SR for 100 E PRATT the map result was dozens of points, most with really low scores.  The correct location had a score of 75.  The results for 200 N HOLLIDAY are similar, if less dramatic.

![100epratt](https://cloud.githubusercontent.com/assets/9657650/4982808/8f4fed60-6915-11e4-8159-7df795ce15d7.png)

**Comment by JMurk** [comment]
This can probably be adjusted in the Geocoding service.  Right now this is looking at Motorola's.  When we create our own, I will look to push the minimum thresholds up some.

**Comment by JMurk** [comment]
Closing this for now... Future fix.
